### PR TITLE
New layout for preferences page and case insensitive searching

### PR DESCRIPTION
**Pull request by sometoby**
Since this is a rather big change, I would recommend not to put it into a release until it has been tested thoroughly.

### CODE REVIEW

**Comment by jvenant** [comment]
Really good new preferences dialog box. 
Others refactoring looks good too.
Gonna do some tests and merge after.
Thank you very much

**Comment by sometoby** [comment]
Please don't merge this yet, I still want to make one or two minor adjustments to the layout. I'll post another comment when I'm finished.

**Comment by jvenant** [comment]
Ok, no problem. Take your time

**Comment by sometoby** [comment]
I'm finished, you can go ahead and test/merge now!

**Comment by phryneas** [comment]
just installed the new version. that's beauftiful, thank you!

**Pull request merged**
