### PR TITLE
Changes in interface

### PR DESCRIPTION
**Pull request by horosgrisa**

### CODE REVIEW

**Comment by sometoby** [comment]
Could you please elaborate more on what this change is intended to do?

**Comment by horosgrisa** [comment]
Small change: type of search box now is 'search', and removed menu separator.
2015-06-24-174903_3046x1050_scrot

**Comment by sometoby** [comment]
Changing the type of the textbox to 'search' does not seem to actually do anything. Is there a good reason for the change? According to MDN, all this does is make the textbox emit the command event when keystrokes happen. Changing the type would only make sense if we were listening for the command event, which we are not.
As for removing the separator, @jvenant has the ultimate authority on visual changes.
I would also like to remind you once more to review your changes thoroughly before sending pull requests. As a maintainer, I get notifications about issue and PR updates on this project, and receiving multiple emails for one PR gets a little annoying.

**Comment by sometoby** [comment]
I'd like to merge #83 sometime soon. It'd be great if you could put the separator back so I can merge this change and then rebase my own changes onto the new master. If the removal of the separator is really important to you, please send another pull request for @jvenant to review.

Also, for small changes like this, a simple issue would be sufficient. It's much easier for everyone involved when no one needs to do unnecessary rebases/merges. Once a solution has been agreed on, a maintainer can just make the change in the master branch.

**Comment by jvenant** [comment]
Transforming the input type from text to search make sens I think because semantically, it is a search field. So even if we don't use the command event, I think it goes in the good way. (And I like the search icon ^_^)

For the separator, removing unnecessary elements makes the interface simpler so it's ok too

I'm a little bit more concerned about changing the "keyup" listener to a "input" listener because the behavior of those two events slightly differ. Especially concerning special keys like arrows, shift, ctrl...
Possibly, removing the "if(event.keyCode <= 46) return false;" lines may be enough. We have to check that.

But any way, making @sometoby refactoring/clean up work easier is currently our priority. So testing PR #83 to merge it asap on the master must be done first. We'll see for this PR after.

Thank you for your contribution @horosgrisa. I really appreciate. We will integrate it just after.

**Comment by horosgrisa** [comment]
@jvenant, I found a bug: I have Cyrillic files and passff doesn't shows names correctly
2015-06-24-234343_1366x768_scrot

**Comment by sometoby** [comment]
@horosgrisa The bug is unrelated to this pull request. Please open an issue for this problem.

**Comment by jvenant** [comment]
try using the through shell invocation with --login as shell argument. See #63 for details.
If it still doesn't work, please create an issue for this. PR is not the place for bug report

**Pull request closed without merging**
