### PR TITLE
add german translation

### PR DESCRIPTION
**Pull request by phryneas**

### CODE REVIEW

**Comment by sometoby** [comment]
Thanks! I tried my hand at a German translation, but you did a much better job than me.

**Comment by phryneas** [comment]
By the way, is there some kind of special editor to see the languages side-by-side? Vim is okay for the job, but as soon as strings get added/dropped I think it will get quite messy.

**Comment by sometoby** [comment]
I'm not aware of any editors or tools specifically for Firefox addon localization. We could of course hack up a Vim plugin or a shell script to check these things, but the best bet is probably just doing a quick ```grep -r``` to see if the locale key you're modifying is still being used somewhere.

**Comment by phryneas** [comment]
Well, that would work, too xD

**Pull request merged**
