### PR TITLE
Add russian translation

### PR DESCRIPTION
**Pull request by horosgrisa**
I made Russian translation for this extension.

### CODE REVIEW

**Comment by jvenant** [comment]
Whaou ! Awesome !
Thank you !

**Comment by sometoby** [comment]
@horosgrisa Do you intend to maintain this translation? There might be changes in the future that require new locale strings to be added or old ones to be updated, it would be a bit sad if some translations wouldn't be updated just because we don't have a maintainer who knows the language.

**Comment by horosgrisa** [comment]
OK, I can. I use this extension and I can make changes in future.

**Comment by horosgrisa** [comment]
@sometoby, Yes,  I can. I use this extension and I can make changes in future.

**Pull request merged**
