### PR TITLE
Fix indentation. Added missing translations. Removed unused strings

### PR DESCRIPTION
**Pull request by horosgrisa**

### CODE REVIEW

**Comment by sometoby** [comment]
I just pushed something to master that causes conflicts, would you mind to rebase on the current master so we can merge?

**Comment by phryneas** [comment]
lol, poor jvenant, sudden surge of pull requests xD

**Comment by horosgrisa** [comment]
Please check now

**Comment by sometoby** [comment]
Thank you for your contribution. :)

**Pull request merged**
