### PR TITLE
minor fixes in english translation

### PR DESCRIPTION
**Pull request by phryneas**
I was going through a german translation and some things don't really make sense. Here's a fix.

### CODE REVIEW

**Comment by sometoby** [comment]
Thank you very much.

**Comment by sometoby** [comment]
By the way, if you want to correct a previous commit without creating a new one, look into interactive rebases. I use them all the time to clean up my commits before and even after I send PRs. :)

**Comment by phryneas** [comment]
I usually do, but this was such a simple fix I just did it from the github webinterface. 
And then I screwed up ;)

**Comment by sometoby** [comment]
Oh, alright then. Sorry to underestimate your git-fu. ;)

**Pull request merged**
